I'm sorry, but an uncaught exception occurred.

While running game code:
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\liviu\\AppData\\Roaming/RenPy/CapybarasvsDinosaurs-1708302084\\persistent'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "C:\Users\liviu\Downloads\renpy-8.2.0-sdk\renpy\bootstrap.py", line 359, in bootstrap
    renpy.main.main()
  File "C:\Users\liviu\Downloads\renpy-8.2.0-sdk\renpy\main.py", line 649, in main
    renpy.persistent.update(True)
  File "C:\Users\liviu\Downloads\renpy-8.2.0-sdk\renpy\persistent.py", line 434, in update
    save()
  File "C:\Users\liviu\Downloads\renpy-8.2.0-sdk\renpy\persistent.py", line 455, in save
    renpy.loadsave.location.save_persistent(compressed)
  File "C:\Users\liviu\Downloads\renpy-8.2.0-sdk\renpy\savelocation.py", line 566, in save_persistent
    l.save_persistent(data)
  File "C:\Users\liviu\Downloads\renpy-8.2.0-sdk\renpy\savelocation.py", line 378, in save_persistent
    safe_rename(fn_new, fn)
  File "C:\Users\liviu\Downloads\renpy-8.2.0-sdk\renpy\loadsave.py", line 303, in safe_rename
    os.unlink(new)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\liviu\\AppData\\Roaming/RenPy/CapybarasvsDinosaurs-1708302084\\persistent'

Windows-10-10.0.22621 AMD64
Ren'Py 8.2.0.24012702
Capybaras vs Dinosaurs 1.0
Wed Feb 21 10:01:40 2024
